### ISSUE TITLE
Search with all characters in dropdown not only start with

### ISSUE THREAD

**Issue by omar0141** [romanjrdykyj/select2dot1#29]
the dropdown search not working correctly it is need to search with all characters  in the the text 
example:
i have list like this : ["usa","edu",tech,"value"]
if i want to get the "test" in the search i should start search with "t" to get results but if i tried to start my search with h it isn't getting any results

**Comment by romanjrdykyj** [comment]
Done

**Comment by romanjrdykyj** [comment]
Done
